Filter in grid view
darianesquivel/catalog-test pull request #90
Opened 2023-04-04 18:42 UTC by darianesquivel

2023-04-04 20:54 UTC, lucasdevferreira requested changes

2023-04-04 20:54 UTC, lucasdevferreira commented on client/src/components/GridViewFilter.tsx
> +type Tprops = {
If this component only works with these two properties, i think it should have a the type of each one instead of `any`. There should not be problems with typing them

2023-04-04 20:54 UTC, lucasdevferreira commented on client/src/components/GridViewFilter.tsx
> +         let include = othersColors.some((el: any) => colorName.includes(el));
I think the name could be changed to `isSelected` instead of `include` ( this one is rather generic ). And also it could be a constant since the value is not changed below

2023-04-04 20:54 UTC, lucasdevferreira commented on client/src/components/GridViewFilter.tsx
> +   const colors: any = [];
These constants could be typed as ` string []` and initialized with  `[' ']`

2023-04-05 12:53 UTC, lucasdevferreira commented
Nice to have: 
* Save the filters made within the url so that the filter could be shared and also be rectrieved when the page changes
* Show the number of items in that view in order to see how many products we have when applying the filters

2023-04-05 15:36 UTC, esquiveldarian commented on client/src/components/GridViewFilter.tsx
> +   const colors: any = [];
Done ✅

2023-04-05 15:37 UTC, darianesquivel commented on client/src/components/GridViewFilter.tsx
> +   const colors: any = [];
Done ✅

2023-04-05 15:41 UTC, darianesquivel commented on client/src/components/GridViewFilter.tsx
> +         let include = othersColors.some((el: any) => colorName.includes(el));
i agree, Done ✅

2023-04-05 16:14 UTC, darianesquivel commented on client/src/components/GridViewFilter.tsx
> +type Tprops = {
I was able to change the type of the function, but I could not do anything with data, because it says it is read-only.

2023-04-06 17:47 UTC, merged